export const verbData = [
    {
      verb: 'Eat',
      base: 'eat',
      pastSimple: 'ate',
      pastParticiple: 'eaten',
      presentParticiple: 'eating',
      telugu: {
        base: 'తింటు',
        pastSimple: 'తినింది',
        pastParticiple: 'తినబడినది',
        presentParticiple: 'తింటున్నాడు',
      },
    },
    {
      verb: 'Sleep',
      base: 'sleep',
      pastSimple: 'slept',
      pastParticiple: 'slept',
      presentParticiple: 'sleeping',
      telugu: {
        base: 'నిద్రించు',
        pastSimple: 'నిద్రించాడు',
        pastParticiple: 'నిద్రించినది',
        presentParticiple: 'నిద్రించుతున్నాడు',
      },
    },
    {
      verb: 'Run',
      base: 'run',
      pastSimple: 'ran',
      pastParticiple: 'run',
      presentParticiple: 'running',
      telugu: {
        base: 'పరుగు',
        pastSimple: 'పరిగా',
        pastParticiple: 'పరుగు',
        presentParticiple: 'పరుగుతున్నాడు',
      },
    },
    {
      verb: 'Walk',
      base: 'walk',
      pastSimple: 'walked',
      pastParticiple: 'walked',
      presentParticiple: 'walking',
      telugu: {
        base: 'నడక',
        pastSimple: 'నడిపడు',
        pastParticiple: 'నడిపడిన',
        presentParticiple: 'నడకుతున్నాడు',
      },
    },
    // {
    //   verb: 'Jump',
    //   base: 'jump',
    //   pastSimple: 'jumped',
    //   pastParticiple: 'jumped',
    //   presentParticiple: 'jumping',
    //   telugu: {
    //     base: 'దెంగు',
    //     pastSimple: 'దెగుతుంది',
    //     pastParticiple: 'దెగుతుంది',
    //     presentParticiple: 'దెంగుతున్నాడు',
    //   },
    // },
    {
      verb: 'Sing',
      base: 'sing',
      pastSimple: 'sang',
      pastParticiple: 'sung',
      presentParticiple: 'singing',
      telugu: {
        base: 'పాడు',
        pastSimple: 'పాడు',
        pastParticiple: 'పాడు',
        presentParticiple: 'పాడుతున్నాడు',
      },
    },
    {
      verb: 'Dance',
      base: 'dance',
      pastSimple: 'danced',
      pastParticiple: 'danced',
      presentParticiple: 'dancing',
      telugu: {
        base: 'నృత్యం చేయు',
        pastSimple: 'నృత్యం చేస్తుంది',
        pastParticiple: 'నృత్యం చేస్తుంది',
        presentParticiple: 'నృత్యం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Swim',
      base: 'swim',
      pastSimple: 'swam',
      pastParticiple: 'swum',
      presentParticiple: 'swimming',
      telugu: {
        base: 'పూలి',
        pastSimple: 'పూలించు',
        pastParticiple: 'పూలించిన',
        presentParticiple: 'పూలించుతున్నాడు',
      },
    },
    {
      verb: 'Read',
      base: 'read',
      pastSimple: 'read',
      pastParticiple: 'read',
      presentParticiple: 'reading',
      telugu: {
        base: 'చదువు',
        pastSimple: 'చదువు',
        pastParticiple: 'చదువు',
        presentParticiple: 'చదువుతున్నాడు',
      },
    },
    {
      verb: 'Write',
      base: 'write',
      pastSimple: 'wrote',
      pastParticiple: 'written',
      presentParticiple: 'writing',
      telugu: {
        base: 'రాయు',
        pastSimple: 'రాయించు',
        pastParticiple: 'రాయబడిన',
        presentParticiple: 'రాయుతున్నాడు',
      },
    },
    {
      verb: 'Listen',
      base: 'listen',
      pastSimple: 'listened',
      pastParticiple: 'listened',
      presentParticiple: 'listening',
      telugu: {
        base: 'విను',
        pastSimple: 'వినుతూ',
        pastParticiple: 'వినబడిన',
        presentParticiple: 'వినుతున్నాడు',
      },
    },
    {
      verb: 'Speak',
      base: 'speak',
      pastSimple: 'spoke',
      pastParticiple: 'spoken',
      presentParticiple: 'speaking',
      telugu: {
        base: 'మాట్లాడు',
        pastSimple: 'మాట్లాడింది',
        pastParticiple: 'మాట్లాడబడిన',
        presentParticiple: 'మాట్లాడుతున్నాడు',
      },
    },
    {
      verb: 'Watch',
      base: 'watch',
      pastSimple: 'watched',
      pastParticiple: 'watched',
      presentParticiple: 'watching',
      telugu: {
        base: 'చూసు',
        pastSimple: 'చూసింది',
        pastParticiple: 'చూసిన',
        presentParticiple: 'చూసుతున్నాడు',
      },
    },
    {
      verb: 'Learn',
      base: 'learn',
      pastSimple: 'learned',
      pastParticiple: 'learned',
      presentParticiple: 'learning',
      telugu: {
        base: 'కలిగి',
        pastSimple: 'కలిగించు',
        pastParticiple: 'కలిగిన',
        presentParticiple: 'కలిగిస్తున్నాడు',
      },
    },
    {
      verb: 'Teach',
      base: 'teach',
      pastSimple: 'taught',
      pastParticiple: 'taught',
      presentParticiple: 'teaching',
      telugu: {
        base: 'నేర్పుకొను',
        pastSimple: 'నేర్పుచేసింది',
        pastParticiple: 'నేర్పుచేసిన',
        presentParticiple: 'నేర్పుచేస్తున్నాడు',
      },
    },
    {
      verb: 'Buy',
      base: 'buy',
      pastSimple: 'bought',
      pastParticiple: 'bought',
      presentParticiple: 'buying',
      telugu: {
        base: 'ఖరీదు',
        pastSimple: 'ఖరీదించు',
        pastParticiple: 'ఖరీదిన',
        presentParticiple: 'ఖరీదుతున్నాడు',
      },
    },
    {
      verb: 'Sell',
      base: 'sell',
      pastSimple: 'sold',
      pastParticiple: 'sold',
      presentParticiple: 'selling',
      telugu: {
        base: 'విక్రయించు',
        pastSimple: 'విక్రయించింది',
        pastParticiple: 'విక్రయించిన',
        presentParticiple: 'విక్రయించుతున్నాడు',
      },
    },
    {
      verb: 'Cook',
      base: 'cook',
      pastSimple: 'cooked',
      pastParticiple: 'cooked',
      presentParticiple: 'cooking',
      telugu: {
        base: 'వంటగా వాడు',
        pastSimple: 'వంటగా వాడించు',
        pastParticiple: 'వంటగా వాడిన',
        presentParticiple: 'వంటగా వాడుతున్నాడు',
      },
    },
    {
      verb: 'Clean',
      base: 'clean',
      pastSimple: 'cleaned',
      pastParticiple: 'cleaned',
      presentParticiple: 'cleaning',
      telugu: {
        base: 'శుభ్రం చేయు',
        pastSimple: 'శుభ్రం చేస్తుంది',
        pastParticiple: 'శుభ్రం చేస్తుంది',
        presentParticiple: 'శుభ్రం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Drive',
      base: 'drive',
      pastSimple: 'drove',
      pastParticiple: 'driven',
      presentParticiple: 'driving',
      telugu: {
        base: 'డ్రైవ్ చేయు',
        pastSimple: 'డ్రైవ్ చేసింది',
        pastParticiple: 'డ్రైవ్ చేసిన',
        presentParticiple: 'డ్రైవ్ చేస్తున్నాడు',
      },
    },
    {
      verb: 'Drink',
      base: 'drink',
      pastSimple: 'drank',
      pastParticiple: 'drunk',
      presentParticiple: 'drinking',
      telugu: {
        base: 'కుడి',
        pastSimple: 'కుడించు',
        pastParticiple: 'కుడించిన',
        presentParticiple: 'కుడితున్నాడు',
      },
    },
    {
      verb: 'Play',
      base: 'play',
      pastSimple: 'played',
      pastParticiple: 'played',
      presentParticiple: 'playing',
      telugu: {
        base: 'ఆడు',
        pastSimple: 'ఆడు',
        pastParticiple: 'ఆడు',
        presentParticiple: 'ఆడుతున్నాడు',
      },
    },
    {
      verb: 'Cry',
      base: 'cry',
      pastSimple: 'cried',
      pastParticiple: 'cried',
      presentParticiple: 'crying',
      telugu: {
        base: 'కూడు',
        pastSimple: 'కూడు',
        pastParticiple: 'కూడు',
        presentParticiple: 'కూడుతున్నాడు',
      },
    },
    {
      verb: 'Laugh',
      base: 'laugh',
      pastSimple: 'laughed',
      pastParticiple: 'laughed',
      presentParticiple: 'laughing',
      telugu: {
        base: 'నవ్వు',
        pastSimple: 'నవ్వు',
        pastParticiple: 'నవ్వు',
        presentParticiple: 'నవ్వుతున్నాడు',
      },
    },
    {
      verb: 'Study',
      base: 'study',
      pastSimple: 'studied',
      pastParticiple: 'studied',
      presentParticiple: 'studying',
      telugu: {
        base: 'అధ్యయనం చేయు',
        pastSimple: 'అధ్యయనం చేసింది',
        pastParticiple: 'అధ్యయనం చేసిన',
        presentParticiple: 'అధ్యయనం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Open',
      base: 'open',
      pastSimple: 'opened',
      pastParticiple: 'opened',
      presentParticiple: 'opening',
      telugu: {
        base: 'తెరవాలి',
        pastSimple: 'తెరవాలించు',
        pastParticiple: 'తెరవాలించిన',
        presentParticiple: 'తెరవాలితున్నాడు',
      },
    },
    {
      verb: 'Close',
      base: 'close',
      pastSimple: 'closed',
      pastParticiple: 'closed',
      presentParticiple: 'closing',
      telugu: {
        base: 'మూసి',
        pastSimple: 'మూసింది',
        pastParticiple: 'మూసిన',
        presentParticiple: 'మూసితున్నాడు',
      },
    },
    {
      verb: 'Sing',
      base: 'sing',
      pastSimple: 'sang',
      pastParticiple: 'sung',
      presentParticiple: 'singing',
      telugu: {
        base: 'పాడు',
        pastSimple: 'పాడు',
        pastParticiple: 'పాడు',
        presentParticiple: 'పాడుతున్నాడు',
      },
    },
    {
      verb: 'Dance',
      base: 'dance',
      pastSimple: 'danced',
      pastParticiple: 'danced',
      presentParticiple: 'dancing',
      telugu: {
        base: 'నృత్యం చేయు',
        pastSimple: 'నృత్యం చేస్తుంది',
        pastParticiple: 'నృత్యం చేస్తుంది',
        presentParticiple: 'నృత్యం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Swim',
      base: 'swim',
      pastSimple: 'swam',
      pastParticiple: 'swum',
      presentParticiple: 'swimming',
      telugu: {
        base: 'పూలి',
        pastSimple: 'పూలించు',
        pastParticiple: 'పూలించిన',
        presentParticiple: 'పూలించుతున్నాడు',
      },
    },
    {
      verb: 'Read',
      base: 'read',
      pastSimple: 'read',
      pastParticiple: 'read',
      presentParticiple: 'reading',
      telugu: {
        base: 'చదువు',
        pastSimple: 'చదువు',
        pastParticiple: 'చదువు',
        presentParticiple: 'చదువుతున్నాడు',
      },
    },
    {
      verb: 'Write',
      base: 'write',
      pastSimple: 'wrote',
      pastParticiple: 'written',
      presentParticiple: 'writing',
      telugu: {
        base: 'రాయు',
        pastSimple: 'రాయించు',
        pastParticiple: 'రాయబడిన',
        presentParticiple: 'రాయుతున్నాడు',
      },
    },
    {
      verb: 'Listen',
      base: 'listen',
      pastSimple: 'listened',
      pastParticiple: 'listened',
      presentParticiple: 'listening',
      telugu: {
        base: 'విను',
        pastSimple: 'వినుతూ',
        pastParticiple: 'వినబడిన',
        presentParticiple: 'వినుతున్నాడు',
      },
    },
    {
      verb: 'Speak',
      base: 'speak',
      pastSimple: 'spoke',
      pastParticiple: 'spoken',
      presentParticiple: 'speaking',
      telugu: {
        base: 'మాట్లాడు',
        pastSimple: 'మాట్లాడింది',
        pastParticiple: 'మాట్లాడబడిన',
        presentParticiple: 'మాట్లాడుతున్నాడు',
      },
    },
    {
      verb: 'Watch',
      base: 'watch',
      pastSimple: 'watched',
      pastParticiple: 'watched',
      presentParticiple: 'watching',
      telugu: {
        base: 'చూసు',
        pastSimple: 'చూసింది',
        pastParticiple: 'చూసిన',
        presentParticiple: 'చూసుతున్నాడు',
      },
    },
    {
      verb: 'Learn',
      base: 'learn',
      pastSimple: 'learned',
      pastParticiple: 'learned',
      presentParticiple: 'learning',
      telugu: {
        base: 'కలిగి',
        pastSimple: 'కలిగించు',
        pastParticiple: 'కలిగిన',
        presentParticiple: 'కలిగిస్తున్నాడు',
      },
    },
    {
      verb: 'Teach',
      base: 'teach',
      pastSimple: 'taught',
      pastParticiple: 'taught',
      presentParticiple: 'teaching',
      telugu: {
        base: 'నేర్పుకొను',
        pastSimple: 'నేర్పుచేసింది',
        pastParticiple: 'నేర్పుచేసిన',
        presentParticiple: 'నేర్పుచేస్తున్నాడు',
      },
    },
    {
      verb: 'Buy',
      base: 'buy',
      pastSimple: 'bought',
      pastParticiple: 'bought',
      presentParticiple: 'buying',
      telugu: {
        base: 'ఖరీదు',
        pastSimple: 'ఖరీదించు',
        pastParticiple: 'ఖరీదిన',
        presentParticiple: 'ఖరీదుతున్నాడు',
      },
    },
    {
      verb: 'Sell',
      base: 'sell',
      pastSimple: 'sold',
      pastParticiple: 'sold',
      presentParticiple: 'selling',
      telugu: {
        base: 'విక్రయించు',
        pastSimple: 'విక్రయించింది',
        pastParticiple: 'విక్రయించిన',
        presentParticiple: 'విక్రయించుతున్నాడు',
      },
    },
    {
      verb: 'Cook',
      base: 'cook',
      pastSimple: 'cooked',
      pastParticiple: 'cooked',
      presentParticiple: 'cooking',
      telugu: {
        base: 'వంటగా వాడు',
        pastSimple: 'వంటగా వాడించు',
        pastParticiple: 'వంటగా వాడిన',
        presentParticiple: 'వంటగా వాడుతున్నాడు',
      },
    },
    {
      verb: 'Clean',
      base: 'clean',
      pastSimple: 'cleaned',
      pastParticiple: 'cleaned',
      presentParticiple: 'cleaning',
      telugu: {
        base: 'శుభ్రం చేయు',
        pastSimple: 'శుభ్రం చేస్తుంది',
        pastParticiple: 'శుభ్రం చేస్తుంది',
        presentParticiple: 'శుభ్రం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Drive',
      base: 'drive',
      pastSimple: 'drove',
      pastParticiple: 'driven',
      presentParticiple: 'driving',
      telugu: {
        base: 'డ్రైవ్ చేయు',
        pastSimple: 'డ్రైవ్ చేసింది',
        pastParticiple: 'డ్రైవ్ చేసిన',
        presentParticiple: 'డ్రైవ్ చేస్తున్నాడు',
      },
    },
    {
      verb: 'Drink',
      base: 'drink',
      pastSimple: 'drank',
      pastParticiple: 'drunk',
      presentParticiple: 'drinking',
      telugu: {
        base: 'కుడి',
        pastSimple: 'కుడించు',
        pastParticiple: 'కుడించిన',
        presentParticiple: 'కుడితున్నాడు',
      },
    },
    {
      verb: 'Play',
      base: 'play',
      pastSimple: 'played',
      pastParticiple: 'played',
      presentParticiple: 'playing',
      telugu: {
        base: 'ఆడు',
        pastSimple: 'ఆడు',
        pastParticiple: 'ఆడు',
        presentParticiple: 'ఆడుతున్నాడు',
      },
    },
    {
      verb: 'Cry',
      base: 'cry',
      pastSimple: 'cried',
      pastParticiple: 'cried',
      presentParticiple: 'crying',
      telugu: {
        base: 'కూడు',
        pastSimple: 'కూడు',
        pastParticiple: 'కూడు',
        presentParticiple: 'కూడుతున్నాడు',
      },
    },
    {
      verb: 'Laugh',
      base: 'laugh',
      pastSimple: 'laughed',
      pastParticiple: 'laughed',
      presentParticiple: 'laughing',
      telugu: {
        base: 'నవ్వు',
        pastSimple: 'నవ్వు',
        pastParticiple: 'నవ్వు',
        presentParticiple: 'నవ్వుతున్నాడు',
      },
    },
    {
      verb: 'Study',
      base: 'study',
      pastSimple: 'studied',
      pastParticiple: 'studied',
      presentParticiple: 'studying',
      telugu: {
        base: 'అధ్యయనం చేయు',
        pastSimple: 'అధ్యయనం చేసింది',
        pastParticiple: 'అధ్యయనం చేసిన',
        presentParticiple: 'అధ్యయనం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Open',
      base: 'open',
      pastSimple: 'opened',
      pastParticiple: 'opened',
      presentParticiple: 'opening',
      telugu: {
        base: 'తెరవాలి',
        pastSimple: 'తెరవాలించు',
        pastParticiple: 'తెరవాలించిన',
        presentParticiple: 'తెరవాలితున్నాడు',
      },
    },
    {
      verb: 'Close',
      base: 'close',
      pastSimple: 'closed',
      pastParticiple: 'closed',
      presentParticiple: 'closing',
      telugu: {
        base: 'మూసి',
        pastSimple: 'మూసింది',
        pastParticiple: 'మూసిన',
        presentParticiple: 'మూసితున్నాడు',
      },
    },
    {
      verb: 'Sing',
      base: 'sing',
      pastSimple: 'sang',
      pastParticiple: 'sung',
      presentParticiple: 'singing',
      telugu: {
        base: 'పాడు',
        pastSimple: 'పాడు',
        pastParticiple: 'పాడు',
        presentParticiple: 'పాడుతున్నాడు',
      },
    },
    {
      verb: 'Dance',
      base: 'dance',
      pastSimple: 'danced',
      pastParticiple: 'danced',
      presentParticiple: 'dancing',
      telugu: {
        base: 'నృత్యం చేయు',
        pastSimple: 'నృత్యం చేస్తుంది',
        pastParticiple: 'నృత్యం చేస్తుంది',
        presentParticiple: 'నృత్యం చేస్తున్నాడు',
      },
    },
    {
      verb: 'Swim',
      base: 'swim',
      pastSimple: 'swam',
      pastParticiple: 'swum',
      presentParticiple: 'swimming',
      telugu: {
        base: 'పూలి',
        pastSimple: 'పూలించు',
        pastParticiple: 'పూలించిన',
        presentParticiple: 'పూలించుతున్నాడు',
      },
    }
]